import { Command } from 'commander';
import fs from 'fs-extra';
import path from 'path';
import chalk from 'chalk';
import { FenceContext } from '../types';

export const ejectCommand = new Command('eject')
  .description('Eject vibe rules to a prompt file')
  .option('-t, --target <type>', 'Output target: markdown | cursor | copilot', 'markdown')
  .action(async (options) => {
    const root = process.cwd();
    const contextPath = path.join(root, '.fence/context.json');
    
    if (!fs.existsSync(contextPath)) {
      console.log(chalk.red('❌ No context found. Run "fence scan" first.'));
      return;
    }

    const context: FenceContext = await fs.readJSON(contextPath);
    const target = options.target.toLowerCase();

    console.log(chalk.blue(`🚀 Ejecting vibe context for target: ${chalk.bold(target)}`));

    try {
      if (target === 'cursor') {
        await generateCursorRules(root, context);
      } else if (target === 'copilot') {
        await generateCopilotInstructions(root, context);
      } else {
        // Default: Markdown
        await generateMarkdownPrompt(root, context);
      }
    } catch (e) {
      console.error(chalk.red('❌ Eject failed:'), e);
    }
  });

/**
 * Generator 1: 通用 Markdown Prompt (VIBE_PROMPT.md)
 * 适合直接喂给 Claude Project, ChatGPT, 或作为 Docs
 */
async function generateMarkdownPrompt(root: string, ctx: FenceContext) {
  const content = `# Project Vibe Context: ${ctx.projectInfo.name}
> Generated by Team Vibe Fence at ${ctx.generatedAt}

## 1. Vibe Coding Guidelines
You are an expert developer working on **${ctx.projectInfo.name}**. 
When writing code, you MUST adhere to the following visual and structural patterns.

### 🎨 Design Tokens (Shadow Style)
The following colors and values are dominant in this codebase. PREFER existing tokens over arbitrary values.
${ctx.tokens.filter(t => t.type === 'color').slice(0, 20).map(t => `- \`${t.value}\` (used ${t.count} times)`).join('\n')}

### 🏗️ Component Library
Don't reinvent the wheel. Use these existing components:
${ctx.components.map(c => `- **<${c.name} />**: ${c.filePath} ${c.fingerprint.constraints.hasFixedDimensions ? '(⚠️ FIXED SIZE)' : ''}`).join('\n')}

## 2. Layout Safety Warnings
The following components have **rigid dimensions** (fixed width/height). 
**DO NOT** place variable-length text inside them without overflow handling:
${ctx.components
    .filter(c => c.fingerprint.constraints.hasFixedDimensions)
    .map(c => `- ${c.name}`)
    .join('\n') || '- None detected (Safe)'}

## 3. Style Patterns
Common Tailwind patterns detected:
${getCommonPatterns(ctx).map(p => `- \`${p}\``).join('\n')}
`;

  const outputPath = path.join(root, 'VIBE_PROMPT.md');
  await fs.writeFile(outputPath, content);
  console.log(chalk.green(`✅ Generated: ${chalk.underline('VIBE_PROMPT.md')}`));
  console.log(chalk.gray(`   💡 Tip: Add this file to your AI chat context (Cursor @file, Claude Project, etc.)`));
}

/**
 * Generator 2: Cursor (.cursorrules)
 */
async function generateCursorRules(root: string, ctx: FenceContext) {
  const content = `# Vibe Fence Rules for ${ctx.projectInfo.name}

You are an expert developer. Follow these style constraints:

## 🎨 Colors
${ctx.tokens.filter(t => t.type === 'color').slice(0, 50).map(t => t.value).join(', ')}

## 🧩 Components
${ctx.components.map(c => `- <${c.name} />`).join('\n')}

## ⚠️ Layout Constraints
Rigid components (Do not overflow): ${ctx.components.filter(c => c.fingerprint.constraints.hasFixedDimensions).map(c => c.name).join(', ')}
`;

  const outputPath = path.join(root, '.cursorrules');
  await fs.writeFile(outputPath, content);
  console.log(chalk.green(`✅ Generated: ${chalk.underline('.cursorrules')}`));
}

/**
 * Generator 3: GitHub Copilot
 */
async function generateCopilotInstructions(root: string, ctx: FenceContext) {
  const dir = path.join(root, '.github');
  await fs.ensureDir(dir);
  const outputPath = path.join(dir, 'copilot-instructions.md');
  
  // 复用 Markdown 逻辑，或者定制化
  const content = `Use the following context for code generation:\n\n` + 
                  `Preferred Colors: ${ctx.tokens.filter(t => t.type === 'color').map(t => t.value).join(', ')}`;
                  
  await fs.writeFile(outputPath, content);
  console.log(chalk.green(`✅ Generated: ${chalk.underline('.github/copilot-instructions.md')}`));
}

// Helper
function getCommonPatterns(ctx: FenceContext): string[] {
    const patternMap = new Map<string, number>();
    ctx.components.forEach(c => {
        c.fingerprint.stylePatterns.forEach(p => {
            patternMap.set(p, (patternMap.get(p) || 0) + 1);
        });
    });
    return Array.from(patternMap.entries())
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(([p]) => p);
}